"""Add plan_type to Lojas

Revision ID: fe7e78f9a4e2
Revises: 68049abf5cf6
Create Date: 2026-03-12 22:06:55.257478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe7e78f9a4e2'
down_revision = '68049abf5cf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lojas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lojas', schema=None) as batch_op:
        batch_op.drop_column('plan_type')

    # ### end Alembic commands ###
